#!/usr/bin/python
# coding=UTF-8

from __future__ import print_function

""" diff JSON files """

__date__ = '2016-03-01'
__author__ = 'Fabian Sandoval Saldias'
__email__ = 'fabianvss@gmail.com'

import argparse
from DiffJson import *

def main():
    parser = argparse.ArgumentParser( description='Diff JSON files.\n\n'
        'You can navigate the JSON before comparison with --path or --path1/2.\n'
        'You can deserialize a string value while navigating.\n'
        'Example: diffjson --path Root.*JsonString.Going.Deeper a.json b.json',
        formatter_class = argparse.RawTextHelpFormatter
        )
    parser.add_argument( 'file1', type = argparse.FileType('r') )
    parser.add_argument( 'file2', type = argparse.FileType('r') )
    parser.add_argument( '--path', '-p', type = str, help = 'Common root path for both files' )
    parser.add_argument( '--path1', '-1', type = str, help = 'Sub path for file1' )
    parser.add_argument( '--path2', '-2', type = str, help = 'Sub path for file2' )
    parser.add_argument( '--path-delimiter', '-d', type = str, default = '.', help = 'Default: %(default)s' )
    parser.add_argument( '--path-deserialize-operator', '-z', type = str, default = '*', help = 'Default: %(default)s' )
    parser.add_argument( '--no-color', action = 'store_true' )
    parser.add_argument( '--no-header', action = 'store_true' )
    parser.add_argument( '--indentation', '-i', type = int, default = 0 )
    args = parser.parse_args()
    
    color_green = '\033[92m' if not args.no_color else ''
    color_red   = '\033[91m' if not args.no_color else ''
    color_end   = '\033[0m' if not args.no_color else ''
    
    diffJson = DiffJson.fromFiles( args.file1, args.file2 )
    
    # combine args.path and args.path1/2
    if args.path is not None:
        path1 = args.path
        path2 = args.path
        if args.path1 is not None: path1 += args.path_delimiter + args.path1
        if args.path2 is not None: path2 += args.path_delimiter + args.path2
    else:
        path1 = args.path1
        path2 = args.path2
    
    if path1 is not None:
        if not diffJson.select1( path1, args.path_delimiter, args.path_deserialize_operator ):
            print( 'Path "%s" not found in %s.' % (path1, args.file1.name), file = sys.stderr )
            exit( 1 )
    
    if path2 is not None:
        if not diffJson.select2( path2, args.path_delimiter, args.path_deserialize_operator ):
            print( 'Path "%s" not found in %s.' % (path2, args.file2.name), file = sys.stderr )
            exit( 1 )
    
    if not args.no_header:
        location1 = ''
        location2 = ''
        if path1 is not None: location1 = ':' + path1
        if path2 is not None: location2 = ':' + path2
        print( ' ' * args.indentation + '< ' + color_red + args.file1.name + color_end + location1 )
        print( ' ' * args.indentation + '> ' + color_green + args.file2.name + color_end + location2 )
        print( ' ' * args.indentation + '---' )
    
    diffJson.colored = not args.no_color
    diffJson.printDiff( args.indentation )

if __name__ == '__main__': main()