#!/usr/bin/python
# coding=UTF-8

""" diff JSON files """

__date__ = '2016-03-01'
__author__ = 'Fabian Sandoval Saldias'
__email__ = 'fabianvss@gmail.com'

import argparse
from DiffJson import *

def main():
    parser = argparse.ArgumentParser( description='Diff JSON files.' )
    parser.add_argument( 'file1', type = argparse.FileType('r') )
    parser.add_argument( 'file2', type = argparse.FileType('r') )
    parser.add_argument( '--path1', '-1', type = str )
    parser.add_argument( '--path2', '-2', type = str )
    parser.add_argument( '--path-delimiter', '-d', type = str, default = '.' )
    parser.add_argument( '--no-color', action = 'store_true' )
    parser.add_argument( '--no-header', action = 'store_true' )
    parser.add_argument( '--indentation', '-i', type = int, default = 0 )
    args = parser.parse_args()
    
    color_green = '\033[92m' if not args.no_color else ''
    color_red   = '\033[91m' if not args.no_color else ''
    color_end   = '\033[0m' if not args.no_color else ''
    
    diffJson = DiffJson.fromFiles( args.file1, args.file2 )
    
    if args.path1 is not None:
        if not diffJson.select1( args.path1, args.path_delimiter ):
            print >>sys.stderr, 'Path "%s" not found in %s.' % (args.path1, args.file1.name)
            exit( 1 )
    
    if args.path2 is not None:
        if not diffJson.select2( args.path2, args.path_delimiter ):
            print >>sys.stderr, 'Path "%s" not found in %s.' % (args.path2, args.file2.name)
            exit( 1 )
    
    if not args.no_header:
        print( ' ' * args.indentation + '< ' + color_red + args.file1.name + color_end )
        print( ' ' * args.indentation + '> ' + color_green + args.file2.name + color_end )
        print( ' ' * args.indentation + '---' )
    
    diffJson.colored = not args.no_color
    diffJson.printDiff( args.indentation )

if __name__ == '__main__': main()