#!/usr/bin/python

import json
import copy
from collections import OrderedDict
import argparse
import sys
from DiffJson import *

def checkJson( original, modified ):
    _checkJsonDict( '', original, modified )

def main():
    parser = argparse.ArgumentParser( description='Diff JSON files.' )
    parser.add_argument( 'file1', type = argparse.FileType('r') )
    parser.add_argument( 'file2', type = argparse.FileType('r') )
    parser.add_argument( '--no-color', action = 'store_true' )
    parser.add_argument( '--no-header', action = 'store_true' )
    parser.add_argument( '--indentation', '-i', type = int, default = 0 )
    args = parser.parse_args()
    
    color_green = '\033[92m' if not args.no_color else ''
    color_red   = '\033[91m' if not args.no_color else ''
    color_end   = '\033[0m' if not args.no_color else ''
    
    if not args.no_header:
        print( ' ' * args.indentation + '< ' + color_red + args.file1.name + color_end )
        print( ' ' * args.indentation + '> ' + color_green + args.file2.name + color_end )
        print( ' ' * args.indentation + '---' )
    
    diffJson = DiffJson.fromFiles( args.file1, args.file2 )
    diffJson.colored = not args.no_color
    diffJson.printDiff( args.indentation )

if __name__ == '__main__': main()